experimental fix for 'aux' joining
(259, 1) joined with (150, 1) was expanded to (259, 150) by the limrad option
before the actual vstack command.
Caused
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1